---
- name: Testing Automation Hub
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  tasks:
    - name: set namespace collections
      ah_namespace:
        name: abc15
        company: Redhat
        email: user@example.com
        avatar_url: https://static.redhat.com/libs/redhat/brand-assets/latest/corp/logo.svg
        description: string
        resources: "# Redhat\nA Namespace test with changes"
        links:
          - name: "New_Google"
            url: "http://www.google.com"
        groups:
          - name: system:partner-engineers
            object_permissions:
              - "change_namespace"
              - "upload_to_namespace"
        ah_server: http://192.168.122.47:8002
        ah_token: 8e2dd98179f6b07075ef3ca8a27d97b307560a04
        validate_certs: false
      register: test
      ignore_errors: true

    - debug:
        var: test


# galaxy token 8e2dd98179f6b07075ef3ca8a27d97b307560a04
# galaxy_server: http://192.168.122.47:8002
# galaxy http://192.168.122.47:8002/api/automation-hub/v3/namespaces/
# system:partner-engineers = default group
# ah server https://192.168.122.200/api/galaxy/
# ah token d04c3ff5c88122c827b3023e9a773c70662c65b6
# ah https://192.168.122.200/api/galaxy/v3/namespaces/
# admins = default group
