---
- name: Testing Galaxy
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - redhat_cop.ah_configuration
  pre_tasks:
    - name: Include vars from ah_configs directory
      include_vars:
        dir: ./ah_configs
        extensions: ["yml"]
      tags:
        - always

  tasks:
    - name: Authenticate and get an API token
      ah_token:
        ah_host: "{{ ah_host }}"
        ah_username: "{{ ah_username }}"
        ah_password: "{{ ah_password }}"

    - name: Create ansible config file
      include_role:
        name: ansible_config

    - name: Create namespace
      include_role:
        name: namespace

    - name: Deauthenticate
      ah_token:
        ah_host: "{{ ah_host }}"
        ah_token: "{{ ah_token }}"
        state: absent
