---
name: Test collection against galaxy_ng

on: [push, pull_request]

jobs:
  Integration-test:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.6

      # Follow the Development Setup guide here:
      # https://github.com/ansible/galaxy_ng/wiki/Development-Setup

      - name: "Clone galaxy_ng"
        run: cd .github && git clone https://github.com/ansible/galaxy_ng.git

      - name: "Clone ansible-hub-ui"
        run: cd .github && git clone https://github.com/ansible/ansible-hub-ui.git

      - name: Create compose env
        run: |
          cat <<EOT >> .github/galaxy_ng/.compose.env
          COMPOSE_PROFILE=standalone
          DEV_SOURCE_PATH='galaxy_ng'
          ANSIBLE_HUB_UI_PATH='/home/runner/work/ah_configuration/ah_configuration/.github/ansible-hub-ui/'
          EOT

      - name: Display Versions
        run: which python && pip --version && ansible --version

      - name: Build docker image
        run: cd .github/galaxy_ng && ./compose build

      - name: Start database and redis services
        run: cd .github/galaxy_ng && ./compose up -d postgres redis

      - name: Run migrations
        run: cd .github/galaxy_ng && ls -l

      - name: Run migrations
        run: sudo groupadd ansible

      - name: Run migrations
        run: cd .github/galaxy_ng && sudo ./compose run --rm api manage migrate

      - name: Import initial data
        run: cd .github/galaxy_ng && ./compose run --rm -e PULP_FIXTURE_DIRS='["/src/galaxy_ng/dev/automation-hub"]' api manage loaddata initial_data.json

      - name: Start services
        run: cd .github/galaxy_ng && ./compose up -d

      - name: "Perform playbook tests"
        run: ansible-playbook playbooks/testing_playbook.yml
